modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues"

[[mods]]
    modId="majruszs_difficulty"
    version="1.3.2"
    displayName="Majrusz's Progressive Difficulty"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsProgressiveDifficultyMod/1.17.1/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"
    logoFile="logo.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Mod which increases the game difficulty of Minecraft after certain events.'''

[[dependencies.majruszs_difficulty]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[2.6.0,3.0.0)"
    ordering="NONE"
    side="BOTH"