modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues"

[[mods]]
modId = "majruszsdifficulty"
version = "1.4.2"
displayName = "Majrusz's Progressive Difficulty"
updateJSONURL = "https://raw.githubusercontent.com/Majrusz/MajruszsProgressiveDifficultyMod/1.19/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"
logoFile = "logo.png"
credits = "Thanks for all your support!"
authors = "Majrusz"
description = '''Mod which increases the game difficulty of Minecraft after certain events.'''

[[dependencies.majruszsdifficulty]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.majruszsdifficulty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.majruszsdifficulty]]
modId = "majruszlib"
mandatory = true
versionRange = "[2.7.2,3.0.0)"
ordering = "NONE"
side = "BOTH"