modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues"

[[mods]]
    modId="majruszs_difficulty"
    version="0.6.0"
    displayName="Majrusz's Progressive Difficulty"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsProgressiveDifficultyMod/1.16.4/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"
    logoFile="logo.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Mod which increases the game difficulty of Minecraft after certain events.'''

[[dependencies.majruszs_difficulty]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszs_difficulty]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[1.6.0,2.0.0)"
    ordering="NONE"
    side="BOTH"