modLoader="javafml"

loaderVersion="[34,)"

license="MIT License"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"

[[mods]]

modId="majruszs_difficulty"

version="1.16.3-0.1.2"

displayName="Majrusz's Progressive Difficulty"

updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"

displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty"

logoFile="logo.png"

credits="Thanks for all your support!"

authors="Majrusz"

description='''
Mod which increases the game difficulty of Minecraft after certain events.
'''

[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
